name: evento
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.16.0
  google_sign_in: ^6.2.1
  google_fonts: ^6.1.0
  firebase_storage: ^11.6.0
  cloud_firestore: ^4.14.0
  firebase_core: ^2.24.2
  provider: ^6.1.1
  animations: ^2.0.11
  styled_widget: ^0.4.1
  flash: ^3.1.0
  modal_bottom_sheet: ^3.0.0-pre
  flutter_svg: ^2.0.9
  reactive_forms: ^16.1.1
  intl: '>=0.18.0 <0.19.0'
  table_calendar: ^3.0.9
  geocoding: ^2.1.1
  location: ^5.0.3
  file: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/bulk/